### ISSUE TITLE
500 error when query template parameters are missing.

### ISSUE THREAD

**Issue by laurensdv** [tdt/core#240]
http://ewi.mmlab.be/ba/lijst/ondernemingen gives an 500 error 

while it should indicate that a required parameter is missing. In this case "naam"

should be thus error 400 also I think (catched before it leads to malformed SPARQL query).

**Comment by pietercolpaert** [comment]
This issue is still the case today...

I see 2 todos here:
 * [ ] Checking why the query resolves to what I said ↑
 * [ ] Including machine readable links (e.g., using hydra or http headers) to indicate the variables that can be used as GET parameters

**Comment by coreation** [comment]
Have you actually tried this query in a SPARQL end-point? That's the easiest check I can think of and returns this:

Virtuoso 37000 Error XM029: Free-text expression, line 0: Invalid character in free-text search expression, it may not appear outside quoted string at ?

So the query itself is apparently not valid.

**Comment by pietercolpaert** [comment]
The query is generated from our code... So indeed: the query not being valid is the reason why a 500 is returned and not a 404...

**Comment by coreation** [comment]
So ?naam is the parameter that replaces the parameter ${naam} or something? Iirc it's like a default value when you don't pass a value with the request? If so, it seems we need to change the default value?

**Comment by pietercolpaert** [comment]
Aah, right, indeed!

It seems when we've implemented this, we didn't anticipate on having variables in filters, where changing it to the default parameter gives this 500 error.

### Proposal

Let's come up with an extra keyword where we indicate the part that we want to make optional. E.g., what about this:

```sparql
prefix regorg: <http://www.w3.org/ns/regorg#>
prefix oslo: <http://purl.org/oslo/ns/localgov#>

CONSTRUCT {
  ?company regorg:legalName ?legalname ;
                     regorg:registration ?registration ;
                     oslo:authenticLocation ?location . } 
WHERE {
      ?company regorg:legalName ?legalname ;
                         regorg:registration ?registration .
      OPTIONAL { ?company oslo:authenticLocation ?location } .
      ifisset_${naam}{?legalname bif:contains "${naam}"}
```

Where in our PHP code, we remove the line when `${naam}` is not set, and if set, then we use the string between `{}` with `${naam}` replaced

**Comment by coreation** [comment]
I like the proposal, but that's going to require some work ;) This will also need some proper documentation and scalability (other use cases for optional behaviour?)

**Comment by pietercolpaert** [comment]
RE work: I believe it's just adding 1 regex replace before the query gets send to the sparql endpoint? I believe I will be able to commit that myself ;)

RE documentation: indeed... we'll need to document that. I'll also take up that task

RE scalability: good point! I believe we could summarize wanted behaviour as follows:
 * _Optional parameter_, if not given, disregard the line (solved by ifisset), but in the response, be sure to add info how to set it (not done right now)
 * _Required parameter_: if not set, return error message with machine readable info how to set it (not implemented right now)

Other uses of optional parameters could be: a FILTER on a date, a part of a regex, a geo-search where you add a bounding box, adding a part of a URI, etc.

**Comment by coreation** [comment]
Jep, and that might be put into an entire new class which handles SPARQL queries, because atm everything is done in the SPARQL reader if I recall that correctly :).

**Comment by pietercolpaert** [comment]
Would also be cool to have a keyword `ifnotset` which does the opposite of `ifisset`

**Comment by coreation** [comment]
Alright, this has been implemented as followed:

ifisset(var){The piece of query you want to include if var is set in the query string}
ifnoset(var){The piece ..... if not set in the query string}

**Comment by pietercolpaert** [comment]
Alright! \o/

Going to test right away :)

**Comment by pietercolpaert** [comment]
Works! Still https://github.com/tdt/docs/issues/31 should be fixed though
