### ISSUE TITLE
Extra feature: support for formatting SPARQL results as HTML table?

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#241]
Moved @laurensdv 's issue from tdt/triples (https://github.com/tdt/rdf2html/issues/1) to here

A HTML table displaying the results could be also of interest for sharing the results of the SPARQL query as such, e.g. to use it as a reference/catalogue/list online without further need of a view or application to build on top of it.

**Comment by coreation** [comment]
Which is only possible with the results of a select query, correct?

**Comment by pietercolpaert** [comment]
indeed
