### ISSUE TITLE
Spatial transformations only for SHP

### ISSUE THREAD

**Issue by JayQueue** [tdt/core#244]
XLS/CSV files can contain XY coordinates and it would be nice to use the epsg parameter to transform to other spatial references.

**Comment by pietercolpaert** [comment]
@coreation if you think we should do this for the 6.0 release, can you assign it?

**Comment by coreation** [comment]
Not sure if we're going to implement this though, I'm not too fond of on the fly translations of projections. Also the added complexity of defining 1 or 2 columns that can be used as a long, lat, the other way around, or a more complex structure such as a path also adds to my "will not solve" here.

**Comment by coreation** [comment]
So @JayQueue Jep nice thought, but this will be done in a different project (more ETL style).
