### ISSUE TITLE
Not able to add dataset using GUI

### ISSUE THREAD

**Issue by aborruso** [tdt/core#263]
Hi,
datatank seems amazing :)

I have installed it and when I try do add a csv resource I have " The resource name field is required." error. But I have set a resource name.

This is a today cloned version.

Thank you

![2014-12-30_19h23_27](https://cloud.githubusercontent.com/assets/30607/5581371/6bb2f9fe-9059-11e4-963b-bdecca562717.png)

**Comment by stilkin** [comment]
Have stared at this error for a while as well, somehow this specific post did **not** turn up in most Google searches on the topic. Maybe a small explanation below the *Identifier* field (or in the manual) is in order?

Thanks for a good question and a quick answer!
