### ISSUE TITLE
Primary key

### ISSUE THREAD

**Issue by aborruso** [tdt/core#269]
Hi,
to set a Primary key for CSV do I must insert the column number of the primary key? Is 1 for the first column and so on?

Thank you

**Comment by coreation** [comment]
Yes, but the numbering starts with 0 :).

On Thu, Jan 1, 2015 at 4:20 PM, Andrea Borruso <notifications@github.com>
wrote:

> Hi,
> to set a Primary key for CSV do I must insert the column number of the
> primary key? Is 1 for the first column and so on?
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tdt/core/issues/269>.
>



-- 
Met vriendelijke groeten,

Jan Vansteenlandt
