### ISSUE TITLE
feature request: add elements to dataset default view page

### ISSUE THREAD

**Issue by aborruso** [tdt/core#270]
Hi,
I think it would be very useful to have in the dataset default view page at least the dasaset license (if it exists), because as you know it's not really open data if there is not a license.
I know that I can read it in the dataset definition, but I think it should be important also to have it in the front-end.

I would like also to have the possibility to read also in the front-end these fields (when these exist): Date, Theme, Publisher URI, Publisher name and Keywords.

As usual, thank you

**Comment by coreation** [comment]
The license is indeed very handy, I'll just add this to the list page. Later on I'd like to re-assemble the list to a theme based categorization, instead of a plain list as it is now.

**Comment by pietercolpaert** [comment]
@NtynMichiel Is this still going to be fixed by today?

**Comment by pietercolpaert** [comment]
@NtynMichiel Now it's in the main page of The DataTank, but not in the HTML view of a dataset... Could this also be added there?

**Comment by NtynMichiel** [comment]
1b78ed104daf373af8b160afdb7b749b6a40fdbc
