### ISSUE TITLE
Feature request: add Character encoding parameter in add dataset page

### ISSUE THREAD

**Issue by aborruso** [tdt/core#271]
Hi,
I have added this CSV dataset via its URL (http://www.comune.palermo.it/js/server/uploads/opendata/_22022013192734.csv) and I have some encoding problem:
![2015-01-01_19h58_12](https://cloud.githubusercontent.com/assets/30607/5593035/99e51580-91f0-11e4-91eb-792a5df57baa.png)

It's encoding is ISO-8859-15 and the fields separator is ";".

Probably it's necessary Character encoding parameter in add dataset page. What do you think about?

Thank you

**Comment by coreation** [comment]
Hi,

Character encoding is indeed something we will add later on. For now we
only handle utf8 encoded data.

Thanks for all the feedback!

On Thu, Jan 1, 2015 at 8:01 PM, Andrea Borruso <notifications@github.com>
wrote:

> Hi,
> I have added this CSV dataset via its URL (
> http://www.comune.palermo.it/js/server/uploads/opendata/_22022013192734.csv)
> and I have some encoding problem:
> [image: 2015-01-01_19h58_12]
> <https://cloud.githubusercontent.com/assets/30607/5593035/99e51580-91f0-11e4-91eb-792a5df57baa.png>
>
> It's encoding is ISO-8859-15 and the fields separator is ";".
>
> Probably it's necessary Character encoding parameter in add dataset page.
> What do you think about?
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tdt/core/issues/271>.
>



-- 
Met vriendelijke groeten,

Jan Vansteenlandt

**Comment by pietercolpaert** [comment]
Couldn't we add an optional field to the CSV source to indicate the encoding of the source file?

**Comment by coreation** [comment]
Ofcourse, but I'd rather do this for every tabular data source then :)

On Tue, Jan 20, 2015 at 9:18 AM, Pieter Colpaert <notifications@github.com>
wrote:

> Couldn't we add an optional field to the CSV source to indicate the
> encoding of the source file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tdt/core/issues/271#issuecomment-70618872>.
>



-- 
Met vriendelijke groeten,

Jan Vansteenlandt

**Comment by coreation** [comment]
Because we want to push our ETL solution (tdt/input), which will be incorporated in the v6 version, this will only be available in the ETL. It allows for any encoding to be converted to UTF-8 and by default also cleans the UTF-8 string for inconsistencies.
