### ISSUE TITLE
Erro 500 for a specific dataset

### ISSUE THREAD

**Issue by aborruso** [tdt/core#272]
Hi,
I have added this CSV dataset via its URL (http://www.comune.palermo.it/js/server/uploads/opendata/_22022013192734.csv) and I have 500 error when I call it in JSON format.

It's encoding is ISO-8859-15 and the fields separator is ";".

Do you know why?

Thank you

**Comment by coreation** [comment]
Hi @aborruso ,

the json encode functionality of PHP only accepts utf8 data in order to serialize it into a valid JSON string. That's why you get the error.
