### ISSUE TITLE
Deprecate KML, go for geojson?

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#275]
Should we deprecate KML in favor of geojson?

**Comment by coreation** [comment]
If OSM/leaflet supports geoJSON then I'm very much in favor of geoJSON yes.

**Comment by pietercolpaert** [comment]
http://leafletjs.com/examples/geojson.html it does indeed :)

Cool funfact: geojson is supported by github and will show a map as an editor. We could build cool integrations I think.

**Comment by coreation** [comment]
Oh! That is fancy indeed!

**Comment by coreation** [comment]
I think this might lower our labour: https://github.com/arenevier/gisconverter.php

**Comment by pietercolpaert** [comment]
Indeed! Nice! I would fork that repository into tdt/gisconverter and publish it on packagist? (it's BSD license, so just keep the copyright notice in the file somewhere)

**Comment by coreation** [comment]
Just for packagist reasons then?

**Comment by pietercolpaert** [comment]
yes

**Comment by akuckartz** [comment]
Still preferring WKT.

**Comment by pietercolpaert** [comment]
@akuckartz it should be reasonably simple to support that as well, right?
@coreation check https://en.wikipedia.org/wiki/Well-known_text - seems like this gisconvertor should be easily extensible with WKT support?

**Comment by coreation** [comment]
Yes, it has WKT afaik.

**Comment by coreation** [comment]
Implemented WKT and GeoJSON, both validated through online services, so it's good to go in the dev branch.

**Comment by pietercolpaert** [comment]
Great! It's now available as a demo on demo.thedatatank.com:

http://demo.thedatatank.com/csv/geo
→ http://demo.thedatatank.com/csv/geo.geojson
and http://demo.thedatatank.com/csv/geo.wkt
