### ISSUE TITLE
Dynamic columns - tabular resources

### ISSUE THREAD

**Issue by coreation** [tdt/core#281]
Our tabular resources such as CSV save their column configuration in our back-end so that people might add aliases to them. However, when columns are being added or removed, they need to click "Save" in the back-end in order for the datatank to re-parse the columns. 

If this does not happen, then the columns are just added on the basis of the index they had when the last "Save" happened. I suggest that when the datatank sees the columns it parses are different from the columns that are saved (even an index swap e.g. column 1 is now column 2 and vice versa) this configuration overwrites the saved one.

**Comment by pietercolpaert** [comment]
I think this is a good idea: it matches the vision of TDT: it should just work and only in the severest case give an error
