### ISSUE TITLE
2 times dc:issued in census dataset on demo

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#282]
Any idea why there is 2 times dc:issued at the census dataset? http://demo.thedatatank.com/dcat/demo

**Comment by coreation** [comment]
That's because somehow (and I can't seem to reproduce the issue) the resource was added twice. So basically in the graph, 2 entries were added and the issued value was different, resulting in a double one.

I've removed the double from the demo, and the issue resolved itself.
