### ISSUE TITLE
SPARQL validation: allow limit and offset

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#283]
After a discussion we should allow LIMIT and OFFSET in queries and only support paging of the result when there is no LIMIT and/or OFFSET given and the result is longer than 1 page

**Comment by pietercolpaert** [comment]
The only thing that should change right now is making the validator more forgiving

**Comment by coreation** [comment]
Adding here the check if limit and offset are integers.

* [ ] Check if limit and offset are integers
