### ISSUE TITLE
README.md enhancements

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#288]
* [x] URIs, not URI's
 * [x] Add links to other resources (documentation, main website, etc)
 * [x] OKFN → Open Knowledge
 * [ ] enhance copy of the explanation

**Comment by coreation** [comment]
What do you mean by "enhance copy of the explanation"

**Comment by pietercolpaert** [comment]
Yeah, that should've been clearer ;)

You can close this issue, @dobbelsteen should handle this together with creating the website :)
