### ISSUE TITLE
GeoJSON lacks description field

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#289]
In KML, we include a link towards more information about the feature. In GeoJSON, we don't have anything to descripe the feature (point or shape...)

**Comment by coreation** [comment]
The link being opengis.net? Or what do you mean by more information.

**Comment by pietercolpaert** [comment]
A description of a feature: the real data - a name, or a link, or whatever :)

E.g., when we have a point with a long, lat, we can also imagine it having a name or an id in the same file. We also need this in the geojson: otherwise we have no clue what the point is for

**Comment by coreation** [comment]
Fixed this by forking the gisconverter, changed some code that now extracts Placemark > name and Placemark > description out of a KML file to add it to the geoJSON as properties. This is valid geoJSON, test with geojsonlint.
