### ISSUE TITLE
Can't find the file for the installed resource

### ISSUE THREAD

**Issue by brechtvdv** [tdt/core#296]
Seems like the filesystem in Ubuntu 14.04.1 is case-sensitive for directories.

In INSTALLEDController.php, line 22:
```$class_file = app_path() . '/../Installed/' .  $source_definition['path'];```

I could fix this by changing the name of the 'installed'-directory to 'Installed'.

**Comment by coreation** [comment]
This has been fixed in other branches, forgot to merge it apparently. Make the fix and set a pull request :)
