### ISSUE TITLE
Error voor xml data

### ISSUE THREAD

**Issue by daften** [tdt/core#301]
500
Oops, we did something wrong!

Message syntax error, unexpected '[' Class /nfs/webroot/domains/qa.datatank4.gent.be/public_html/app/Tdt/Core/DataControllers/XMLController.php On Line 22 Trace #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main}

Die nieuwe functie getParameters geeft [] terug, which i've never seen. Moest dit mss array() zijn?

**Comment by coreation** [comment]
Well the new version since 4.6 is in php 5.4. Is the current server 5.3?

**Comment by pietercolpaert** [comment]
PHP5.4 supports [] instead of array(). Seems like you're using a PHP version lower than 5.4, which is no longer supported by any linux distribution...

**Comment by daften** [comment]
Zucht, idd :(



--
Dieter Blomme

**Comment by daften** [comment]
Fixed door de 5!!! instanties te vervangen door array()
Nen grep op array() met exclusie van lib en vendor mapkes tonen dat er nog niet echt consistentie is met die nieuwe syntax ;)

**Comment by coreation** [comment]
Indeed, only in the fresh code.

**Comment by coreation** [comment]
Closing this, the error was due to a 5.3 php version, we support 5.4.
