### ISSUE TITLE
Add Flemish open data licenses

### ISSUE THREAD

**Issue by coreation** [tdt/core#302]
The licenses given by the Flemish government should be included in the list of available licenses.

**Comment by pietercolpaert** [comment]
Should this be in the international release of TDT? It would be cool if it would be available as an extra seeder command... No?

**Comment by coreation** [comment]
This would be nice indeed, however you can't pass any variables to the seed command.
Added to that, the seeding of the licenses is embedded in the seeding of all DCAT elements (themes, languages etc.)

So the only way I see this happening is building a stand-alone seed command for licenses (with the availability of choosing a license set with a parameter).

**Comment by coreation** [comment]
See issue #310
