### ISSUE TITLE
SEO and twitter friendly HTML

### ISSUE THREAD

**Issue by pietercolpaert** [tdt/core#305]
Let's add JSON-LD metadata in the HTML views for the purpose of indexing by google. This way, we will have a nicer preview when the page shows up in a search result of google.

In the same JSON-LD, we can add the DCAT triples (quick fix for URI dereferencing of the dcat:Dataset URI).

Let's also add opengraph and twitter metadata to the html for it to be shown as twitter cards, or as a facebook post

**Comment by coreation** [comment]
Any links to the vocabulary that makes up the graph data that should be put in the JSON-LD that google will pick up?

**Comment by pietercolpaert** [comment]
https://developers.google.com/structured-data/rich-snippets/
Seems like google doesn't do rich snippets for datasets yet, yet it is defined in http://schema.org as something that's pretty close to DCAT. See:
http://schema.org/Dataset

**Comment by coreation** [comment]
That schema looks alot like DCAT indeed, a lot of the properties can be provided just by our standard meta-data. As I understand it this should just be a "<script>" tag where the type is application/json+ld?

**Comment by pietercolpaert** [comment]
a "?

**Comment by pietercolpaert** [comment]
Correct!

**Comment by coreation** [comment]
Properties that have been added are (schema:)

datasetTimeInterval
distribution
dateCreate
dateModified
inLanguage
license
description
headline
