### ISSUE TITLE
Create MongoDB resource

### ISSUE THREAD

**Issue by coreation** [tdt/core#306]
Create a MongoDB resource that allows for basic querying (= - operator).

**Comment by coreation** [comment]
Also allow for a full-text like query.

**Comment by coreation** [comment]
Basic querying is made possible by prefixing "q." to a parameter name. This allows for occupied parameters such as limit and offset to be passed to the mongo as well.

**Comment by pietercolpaert** [comment]
I'm concerned with the cacheability of the resources... Shouldn't querying parameters be optional when adding a resource?

**Comment by coreation** [comment]
I'm not sure if allowing simple filter parameters (only '=' is supported atm) will provide so much overhead to implement a "queryable" option.
