### ISSUE TITLE
make it more clear when a dataset is larger than the shown data

### ISSUE THREAD

**Issue by joostschouppe** [tdt/core#314]
Some data users need all the data by default, not a subset. TDT does not make it straightforward to download a whole dataset. A download function should either download the whole dataset, or a give a proper warning when the data is incomplete.

In the dataset viewer, for longer datasets, a 'Next' button is available. This is a good first step (and one that isn't visible in "our" use of TDT at opendata.antwerpen.be ). It might make it even more clear if the URL for these case would be http://demo.thedatatank.com/dbpedia/stations?&offset=0&limit=500 instead of http://demo.thedatatank.com/dbpedia/stations .

However, for a format like csv, I believe the vast majority of datausers will need the whole dataset. Mostly, they will be data analists, not programmers. They aren't able or willing to build something just to be able to easily download the whole dataset (like http://warrieka.github.io/geoplus/index.html ). So why not have this format download the whole data by default?

**Comment by coreation** [comment]
Thanks for the feedback @joostschouppe, we'll see how we can fit this into our next release.

**Comment by coreation** [comment]
Thanks @joostschouppe, this is indeed much more intuitive!

**Comment by joostschouppe** [comment]
Hi,
I recently noticed that the CSV export only loads the first 20.000 records, at least in our Antwerp instance with [this dataset](http://opendata.antwerpen.be/datasets/verkeersborden).

This feature request was only for CSV, but actually we believe 95% of our users actually just want the whole dataset, whatever format they are consulting.
