### ISSUE TITLE
Shapefile examples not working on demo.thedatatank.com

### ISSUE THREAD

**Issue by DieterDePaepe** [tdt/core#316]
```
$ curl http://demo.thedatatank.com/dresden/rivers
{"error":{"type":"api_error","message":"Call to undefined function muka\\ShapeReader\\dbase_open()"}}
```

Browsing to the url gives a generic 500 error page.

**Comment by coreation** [comment]
Thanks for noticing, we added the muka library in the last version iirc, it needs a PHP extension however to access certain methods. I'll see what I can do to add the correct extension.

**Comment by coreation** [comment]
@pietercolpaert seems like our linux distro is EOL, which makes it (currently) not possible to install the dbase extension through pecl (phpize is missing and needs to be installed). Any idea on the course of action?

**Comment by pietercolpaert** [comment]
Our ubuntu version is now 13.10. I think upgrading to ubuntu 14.04 should be no issue. I'll do this one of these days!

**Comment by DieterDePaepe** [comment]
Are you referring to the dbase extention (as described on https://github.com/muka/ShapeReader)? In my Ubuntu 14.04 setup, dbase is present. Still, I receive the following error:

```
[Fri Aug 21 13:58:49.474902 2015] [:error] [pid 4145] [client 127.0.0.1:52827] PHP Fatal error:  Class 'muka\\ShapeReader\\ShapeReader' not found in /var/www/tdt/core/app/Tdt/Core/DataControllers/SHPController.php on line 100, referer: http://localhost/
```

It looks like an incorrect import. I've tried looking for the cause, but my php wizardry is not strong enough to find the problem.

**Comment by coreation** [comment]
And you have it added to your php.ini file? dbase.so should be added there and make sure to restart your  apache.

**Comment by DieterDePaepe** [comment]
I've added it the conf.d folders:

```
dieter@dieter-VB-TDT:~$ cat /etc/php5/cli/conf.d/20-dbase.ini 
extension=dbase.so
dieter@dieter-VB-TDT:~$ cat /etc/php5/apache2/conf.d/20-dbase.ini 
extension=dbase.so
```

I assume the following command proves that it works:
```
dieter@dieter-VB-TDT:~$ php -m | grep dbase
dbase
```

**Comment by coreation** [comment]
Im not sure if -m lists all available modules or configured (active) modules, make sure that it's in your php.ini file, the dbase.ini file is probably some ini file for dbase specifically (which you don't -afaik- have to touch).

**Comment by DieterDePaepe** [comment]
I added `extension=dbase.so` to the apache2 php.ini and restarted the service. Still the same error.

**Comment by coreation** [comment]
En nu nog composer update doen, de fout die je krijgt zegt dat je de shapereader (die de dbase.so extensie gebruikt) niet kan vinden. Composer update installeert de laatste dependencies. Git pull -> trekt nieuwe updates binnen, met ook configuraties van nieuwe dependencies, composer update kijkt naar de dependencies en installeert ze.

**Comment by DieterDePaepe** [comment]
That did it! Hadn't thought of this because I already saw the muka package in the vendor directory, but the composer update did download a new version of it (and some other packages).

2 further remarks I'd like to share:
- The apache logging mentioned that dbase was being loaded twice. So php.ini and conf.d/dbase.so both do the same thing.
- I had to re-seed the database, because I got an `{"error":{"type":"api_error","message":"Undefined index: deleted"}}` response. (Maybe I should have done artisan migrate?)

**Comment by coreation** [comment]
Ah yes! artisan migrate as well :)

**Comment by coreation** [comment]
Seems like more data is being read now as well, if you're experiencing an error still (or on your localhost) re-add the resource and you should be ok. All is well now on the demo instance.

**Comment by netsensei** [comment]
I just stumbled upon this error while trying to get `phpunit` on Homestead working.

Looks to me like this is an explicit dependency. Since it breaks tests: shouldn't this be documented in some sort of requirements section in the README?

Unless you try to import shapefiles, you probably won't encounter any problems. If you do: this might be tricky to debug if you are unaware of what causes this error.

**Comment by coreation** [comment]
You're talking about the dbase.so extension @netsensei?

**Comment by netsensei** [comment]
Yep. I had to perform the same steps as @DieterDePaepe. Homestead is based on Ubuntu, I believe.
