### ISSUE TITLE
Additional distributions per dataset

### ISSUE THREAD

**Issue by DieterDePaepe** [tdt/core#319]
In the demo datatank, only the JSON representation of each data set is present in the DCAT feed. Pieter told me the reason for this is that TDT will converge to using mainly JSON as output in the future.

I would like to suggest 2 changes to this:
- I feel the original data set should also be exposed. Since the JSON conversion might introduce errors, it could be possible that it's impossible to get a valid linked dataset using the DCAT.
- Shapefiles (or other geographic formats) should also have a GeoJSON distribution.

Let's discuss? :)

**Comment by coreation** [comment]
Hi Dieter,

* A "download the original file" could indeed be useful.
* Shapefiles already have a GeoJSON format iirc, even WKT. Additional buttons are provided to facilitate links to these formats.

I'll have to look into to how easy it would be to facilitate your first suggestion, or you can do so yourself ;)

**Comment by DieterDePaepe** [comment]
Hi Jan,

I'm talking about the listings in the DCAT feed. Currently, only JSON is present, even for shape files. (See in http://demo.thedatatank.com/api/dcat)

Can't promise anything yet, it will depend on my time allocations. ;)

**Comment by coreation** [comment]
Ah, it would indeed be better if we added GeoJSON there. The point of only adding JSON was to provide the (or rather gently push) user to use modern formats. But GeoJSON would be more fitting for geo-related data.

* [ ] Make the distribution of geo-related data in the DCAT feed GeoJSON instead of JSON

**Comment by DieterDePaepe** [comment]
Awesome! But how about also including a dcat:distribution for the original dataset?

**Comment by pietercolpaert** [comment]
Should be optional if implemented. You don't always want to exposé your entire back-end or file source

**Comment by DieterDePaepe** [comment]
@pietercolpaert If you're already exposing the data in a JSON format, why not expose the source file too? If you want to limit what data is being exposed, shouldn't this be a general feature (and not just related to the DCAT)? So that you can explicitly decide which formats you expose?

**Comment by pietercolpaert** [comment]
@DieterDePaepe examples:
 * an excel file where 1 specific sheet is selected to be opened
 * a MySQL database
 * a file on an intranet
 * ...

**Comment by coreation** [comment]
True, however I am in favor of returning the source file (if possible) if the format is exactly the same as the source. e.g. requesting an XML file in XML, a JSON in JSON, KML in KML. It's mainly because every XML based format (XML, KML) get mangled into a non-standard (there is no standard) transformation of non-object oriented formats to object oriented formats. It would be nice to just return the non-object oriented one.

**Comment by pietercolpaert** [comment]
@coreation I agree with that!

**Comment by DieterDePaepe** [comment]
Good examples. So it depends on whether you do some kind of data masking? If so, you don't return the original file, though a file in the origin format containing the masked data could work for some cases.

I don't get the "file on an intranet" example though, are you referring to access restrictions? In this case the datatank could act as a proxy, since it has access to the file anyway.

**Comment by pietercolpaert** [comment]
@DieterDePaepe the data could as well be a file descriptor on a non-www location: `file:///C:\Documents\foobar.xls`

**Comment by DieterDePaepe** [comment]
@pietercolpaert Yes, but since TDT has access to that file and can deliver a JSON version of that file, why couldn't it just serve a proxied version of that file as well? So instead of converting, it would come down to making a copy.

**Comment by pietercolpaert** [comment]
@DieterDePaepe That's indeed what @coreation was suggesting in a later comment and I agreed :D

**Comment by coreation** [comment]
Indeed :)
