### ISSUE TITLE
DCAT syntax error

### ISSUE THREAD

**Issue by tthoeye** [tdt/core#322]
I *think* there may be a syntax error (triple quotes) in the DCAT TTL export, in the description field:
![dcat](https://cloud.githubusercontent.com/assets/1484581/9608254/d18a7a74-50cd-11e5-9b79-70d8c482aa5d.png)

See: http://digipolis-staging.weopendata.com/api/dcat

In any case, the ttl file does not validate with the DCAT Validator due to a "syntax error in the Turtle" file:
![dcatvalidator](https://cloud.githubusercontent.com/assets/1484581/9608322/26f5fa7e-50ce-11e5-8617-2bc294163724.png)

Might be an issue for https://github.com/oSoc15/dcat-validator

**Comment by pietercolpaert** [comment]
It's indeed a turtle serialisation issue... Could be a problem with easyrdf.

Detailed serialisation feedback after test with http://ttl.summerofcode.be/:
```
Error: Expected punctuation to follow ""Specificaties dataset IVAGO-stratenlijst: De dataset IVAGO-stratenlijst bevat onderstaande kolommen met gegevens: Straatnaam : Officiële straatnaam Straatcode : code gebruikt door stad Gent lv : l = landelijk gebied – bewoners bieden hun restafval en GFT aan in containers v = verstedelijkt gebied – bewoners bieden hun restafval aan in gele IVAGO-zakken v/l = een deel van de straat valt in verstedelijkt gebied en een ander deel valt in landelijk gebied; zie de kolommen ‘even van/tot’ en ‘oneven van/tot’ voor de exacte afbakening van straatdelen Sector : IVAGO deelde haar werkingsgebied op in 64 ophaalrondes. De verschillende rondes in Gent krijgen een letter V of L en 2 cijfers. Aan de hand van deze code kan je de straat linken aan de ophaaldagen vermeld in de dataset IVAGO-inzamelkalender. Even van : straten die in 2 sectoren of ophaalrondes vallen krijgen hier een duidelijke afbakening. Het getal duidt op het huisnummer aan de even kant waar de sector (zie kolom sector) begint. opgelet: de codes "-1" en "" at line 1962.

Error: Expected punctuation to follow ""Specificaties dataset IVAGO-stratenlijst: De dataset IVAGO-stratenlijst bevat onderstaande kolommen met gegevens: Straatnaam : Officiële straatnaam Straatcode : code gebruikt door stad Gent lv : l = landelijk gebied – bewoners bieden hun restafval en GFT aan in containers v = verstedelijkt gebied – bewoners bieden hun restafval aan in gele IVAGO-zakken v/l = een deel van de straat valt in verstedelijkt gebied en een ander deel valt in landelijk gebied; zie de kolommen ‘even van/tot’ en ‘oneven van/tot’ voor de exacte afbakening van straatdelen Sector : IVAGO deelde haar werkingsgebied op in 64 ophaalrondes. De verschillende rondes in Gent krijgen een letter V of L en 2 cijfers. Aan de hand van deze code kan je de straat linken aan de ophaaldagen vermeld in de dataset IVAGO-inzamelkalender. Even van : straten die in 2 sectoren of ophaalrondes vallen krijgen hier een duidelijke afbakening. Het getal duidt op het huisnummer aan de even kant waar de sector (zie kolom sector) begint. opgelet: de codes "-1" en "" at line 1962.
```

**Comment by coreation** [comment]
Looks like that's something EasyRdf might do wrong indeed. I'll look into the serialization code, see if I can find anything.

**Comment by coreation** [comment]
Hey @tthoeye and @pietercolpaert check out http://www.w3.org/TR/turtle/ example 11, I think those triples quotes are done so because of the new lines in the literal value. 

Second the description of that ivago datasource is incomplete, it ends with a double quote, and here's where EasyRdf hiccups, because when it ends with a double quote it cannot be embedded with double quotes, apparently that's not built in the serializer, let's see if I can help them out with that :).

**Comment by coreation** [comment]
Added an [issue](https://github.com/njh/easyrdf/issues/252) on their github.

**Comment by coreation** [comment]
Issue was recognized and requested a [pull request](https://github.com/njh/easyrdf/pull/253) with unittest and fix! Now we wait for the merge into the master branch and we can update instances.

**Comment by tthoeye** [comment]
Thanks for looking into this! 
Meanwhile I'll fix the metadata description on our portal :)

**Comment by coreation** [comment]
No problem, I'm still waiting to close this once they merge the [pull request](https://github.com/njh/easyrdf/pull/253). I hope this will get resolved before the 5th of december :).

**Comment by coreation** [comment]
https://github.com/njh/easyrdf/pull/253#event-429036877 \o/
