### ISSUE TITLE
Installed resource: specific configuration?

### ISSUE THREAD

**Issue by netsensei** [tdt/core#331]
So, my custom installed resource fetches data from a - rather complicated - API. Of course, one of the requirements of the API is a passing a registered API key. ([I know!](http://ruben.verborgh.org/blog/2013/11/29/the-lie-of-the-api/))

I wondered if a plugin class can add specific form elements to the general configuration form for an installed resource.  ie. storing an API key as configuration.

The alternative is juggling with plugin specific configuration files or - absolutely last resort - hard code the key in the plugin.

**Comment by coreation** [comment]
Hi @netsensei! You can actually extend the installed resource quite easily (from a core dev perspective). The thing you need to do is entirely back-end, the front-end will adjust.

1/ Make a migration through artisan ([docs](http://laravel.com/docs/4.2))
2/ In that migration add your necessary extra fields (api_key)
3/ Make sure the repository layer notices this change by
   * adding api_key in the installed definition model fillable array 
   * adding api_key in the installed definition repository in the create_parameters array
4/ You're done (I think), doing this all by heart

A much quicker way is to create your own config file under app/config and adding your api_key there, check laravel docs on how to create one, and access the values :).

**Comment by netsensei** [comment]
I went with app/config. Quickest way to store configuration. A complete migration would've been too far a stretch, for now. ;-)
