### ISSUE TITLE
Dataset edit erases non-visible definition attributes

### ISSUE THREAD

**Issue by DieterDePaepe** [tdt/core#332]
I added a dataset in TDT using it's rest api. I filled in the "geo" variables so the Formatter knows where to get the longitude/latitude. Everything working up to now and the geo values were listed in the definition of the dataset. Next I wanted to change the caching mode, so I went to the /api/admin/datasets/edit page to edit this setting. After saving, the "geo" settings had been removed. I'm guessing any value that is not visible in the editor will get erased this way.

**Comment by coreation** [comment]
Hi Dieter,

Yea, you might be correct, need to look into how the patch throws/maintains from the old dataset in order to update it.

**Comment by coreation** [comment]
We have no way of
