### ISSUE TITLE
REST parameters converted to lowercase causes issues

### ISSUE THREAD

**Issue by netsensei** [tdt/core#334]
Hi,

I'm trying to define 2 custom REST calls which are wired to an installed resource. This resource is a proxy for a 3rd party API which is far more complex. (I'm trying to create a simplified, cacheable API which allows for fast retrieving subsets of data.)

The first call is designed to fetch a list of datasets id's. The second call gets passed a specific dataset id and shows the record associated with that id.

Here are the calls:

**1/ /provider/datasets**

Provides a list of datasets. Each dataset is identified with a unique name/id that can be passed to the second call.  Example: 04041_MyDataSetName

**2/ /provider/datasets/04041_MyDataSetName**

This call should return all the records associated with this particular dataset name.

=> Problem:  The Datatank is converting the entire call URI - including the parameter - to lowercase:  04041_MyDataSetName is turned into 04041_mydatasetname.

This is an issue because I'm passing a lowercased version of the id to the original API. Said API doesn't recognise the dataset id and will return an empty response.

Caused by: 

````php
        // Introduce case insensitivity and trim right '/'
        $uri = strtolower(rtrim($uri, '/'));
````
in `app/Tdt/BaseController.php`

Is there a reason why the entire URI - including any params - is converted to lowercase?

**Comment by coreation** [comment]
Hey @netsensei that's because we don't want to make a distinction between /something/dataresource and /Something/dataresource as a means to lead people to think about their URI strategy. Developers however can always get the URI and their parts from the Request class in Laravel which covers any functionality concerning used paths and hostnames.

With that answer can I close this?

**Comment by netsensei** [comment]
Hi,

Yes. That's a good alternative. But then: what's the use case for the `getParameters` and `setParameter` methods in an installed resource?

The Stock example shows us how to define parameters mapped to URL arguments them and reuse them in the `getData()` method via the `parameters` property.  If the data in that property is being altered before it's passed to this method, then we can't rely on this part of the API.

Two strategies: 

* deprecate this part of the API and document that URL data is directly accessible via the Request class.
* Refactor this part of the API so that the `parameters` property gets it's data from the Request class instead of extracting it in the base controller.

The former is probably easiest to accomplish but has problems with backward compatibility, the latter doesn't alter the API but requires bit more work.

**Comment by coreation** [comment]
Aha, I see the problem now :). Refactoring is probably the way to go here as it will ensure backwards compatibility and only results in some extra code.

**Comment by netsensei** [comment]
Submitted a quick fix in a pull request. Great way of delving a bit deeper in the core code.

I've noticed that there's quite some URI parameter handling code like this hard wired inside the data controllers. Maybe it would be a good idea to isolate it in a separate class that can be unit tested?

**Comment by coreation** [comment]
Thanks for the pull request! That might be useful yes, but at this moment we're looking at getting some vital data scaling issues done for the 5.12 release :).
