### ISSUE TITLE
DCAT should output GeoJSON for any geometrical dataset

### ISSUE THREAD

**Issue by DieterDePaepe** [tdt/core#335]
Currently, the DCAT feed only uses GeoJSON for shapefiles. It seems better to do this for any geographical dataset. Some formats are always geographical (shape, kml), others are sometimes (csv, json). I suggest the following changes:

- If a dataset definition has any value for its "geo" attribute, I'd say it's safe to assume it is a geographical file.
- Instead of checking the name of the source_type of a definition against a predefined list, do a code call that returns whether or not the dataset is geographical. This would prevent having to change the predefined list if a user adds new kinds of (geographical) definitions.

The only thing not solved by this are the datasets that aren't marked as geographical, but contain geo information (eg: a csv file without "geo" definition-attributes, but containing lat/lon attributes in the data). But I guess this is acceptable given that this is all a best-effort.

**Comment by pietercolpaert** [comment]
small remark: while I agree with this issue, I would still like to see the plain JSON as an alternative to the geojson, and not make geojson take over the .json extension here.

**Comment by akuckartz** [comment]
GeoJSON is not compatible with Linked Data.

**Comment by pietercolpaert** [comment]
Indeed, cfr: https://github.com/geojson/geojson-ld/issues/32

**Comment by coreation** [comment]
Isn't it irrelevant for a dataset distribution to be listed as .geojson, even it's not compatible with Linked Data?

**Comment by DieterDePaepe** [comment]
@pietercolpaert Regarding your first remark. Not sure I understand correctly. Do you mean you prefer to see both json and geojson in the DCAT?

Is it a problem that GeoJSON is not (yet) compatible with Linked Data? It simply means the conversion cannot be done, so GeoJSON is not available as a format for LD sources then.

**Comment by pietercolpaert** [comment]
Yes, both.

It's not a problem, no :)

Op vr 25 sep. 2015 13:38 schreef Dieter De Paepe <notifications@github.com>:

**Comment by akuckartz** [comment]
@DieterDePaepe Yes, that is a problem.

**Comment by coreation** [comment]
How so @akuckartz ?

**Comment by akuckartz** [comment]
@coreation How can it not be a problem ?

**Comment by pietercolpaert** [comment]
It's not a problem we need to fix for this issue

**Comment by coreation** [comment]
Indeed, a distribution can be whatever it can be. In our platform we want to endorse the best possible representation, for most datasets this is json, for geographical datasets (imo) it should be geojson like @DieterDePaepe suggested.

**Comment by coreation** [comment]
Going to add something to this issue, which is incorporating the GeoJSON mime-type.

* [ ] Use the application/vnd.geo+json mime-type
