### ISSUE TITLE
EasyRDF dependency not met when installing through packagist

### ISSUE THREAD

**Issue by netsensei** [tdt/core#343]
I tried to install The Datatank via packagist doing a `composer require tdt/core` but I ended up with an unmet dependency: there is no 'dev-devel' version for easyrdf/easyrdf.  Screenshot attached of the error.

<img width="806" alt="easyrdf-tdt" src="https://cloud.githubusercontent.com/assets/105355/10275365/2417ffda-6b47-11e5-8abd-f301232ee25e.png">

**Comment by coreation** [comment]
Hi @netsensei , that should be fixed in the next release, we point to a stable version there :).
