### ISSUE TITLE
Hydra paging

### ISSUE THREAD

**Issue by coreation** [tdt/core#345]
Provide paging headers with the [hydra vocabulary](http://www.hydra-cg.com/spec/latest/core/).

**Comment by akuckartz** [comment]
Some discussions regarding paging are taking place. See https://github.com/HydraCG/Specifications/issues/36

**Comment by coreation** [comment]
Hey @akuckartz thanks for the pointer!

**Comment by coreation** [comment]
This has been implemented in the Link HTTP header.
