### ISSUE TITLE
Add GA 

### ISSUE THREAD

**Issue by coreation** [tdt/core#350]
Add an analytics hook to the dataset calls. This will be implemented with a GA implementation, but should be adjustable with some minor code changes, through dependency injection.

**Comment by pietercolpaert** [comment]
Should we also allow piwik? Just for the sake of not having to depend on GA?

**Comment by coreation** [comment]
We can do that yes, not sure if I'll find the time to implement and test it though.

**Comment by pietercolpaert** [comment]
Let's say people who want to use piwik can do so by pull requesting it  for now ;)

**Comment by coreation** [comment]
I'll make it so you can inject the class then.

**Comment by coreation** [comment]
https://github.com/tdt/core/commit/83f8140a0b30765e767b12aca1b97457e761339c
