### ISSUE TITLE
Merge JSON and JSON-LD

### ISSUE THREAD

**Issue by coreation** [tdt/core#351]
Merge the JSON and JSON-LD, just like the GeoJSON has been implemented.

**Comment by pietercolpaert** [comment]
You mean only on back-end level, right?

**Comment by coreation** [comment]
I also meant in the front-end, where we have a GeoJSON checkbox now, it might as well be a drop down list with GeoJSON and JSON-LD.

**Comment by pietercolpaert** [comment]
Ok! Makes sense
