### ISSUE TITLE
Incorrect COUNT query in SPARQLController if WHERE clause contains 'from'

### ISSUE THREAD

**Issue by erikap** [tdt/core#354]
I created a SPARQL dataset with SPARQL query:

    PREFIX gr: <http://purl.org/goodrelations/v1#>

    SELECT  * 
    WHERE {
      ?s a ?class .
      OPTIONAL { ?s gr:validFrom ?start  }.
      OPTIONAL { ?s gr:validThrough ?end  }.
    } 

Note that the query doesn't contain a `FROM` clause. The `WHERE` clause contains 'from' in one of the predicates.

Retrieving the dataset returns a 500 because the COUNT query created by the SPARQLController is not corret. The error message is:
`The SPARQL endpoint returned a 400 error. If the SPARQL query contained a parameter, don't forget to pass them as a query string parameter. The error was: Virtuoso 37000 Error SP030: SPARQL compiler, line 0: Too many closing parentheses at '}' SPARQL query: define sql:big-data-const 0 #output-format:application/sparql-results+json PREFIX gr: SELECT (count(*) AS ?count) From ?start }. OPTIONAL { ?s gr:validThrough ?end }. }.`

The incorrect COUNT query created by the SPARQLController:
```
PREFIX gr: <http://purl.org/goodrelations/v1#>

 SELECT (count(*) AS ?count) From ?start  }.
  OPTIONAL { ?s gr:validThrough ?end  }.
}
```

**Comment by coreation** [comment]
Hi @erikap Looks like our regex is a bit too greedy, thanks for logging, I'll add it to the 5.12 release.

**Comment by coreation** [comment]
Hey @erikap, this should be fixed now on the dev branch, the regex took the "FROM" from the where clause, it's expression is now set to look for "FROM" statements followed by a <.+> statement. Ideally the ".+" would be a URI scheme but that already that already did the trick :).
