### ISSUE TITLE
Excel file conversion assumes "Sheet1"

### ISSUE THREAD

**Issue by DieterDePaepe** [tdt/core#358]
When converting an excel file to another format, TDT looks for a sheet named "Sheet1". In non-English Excel, the default sheet is named differently and will cause a failed conversion.

It makes more sense to simply take the first sheet (regardless the name) for conversion.

**Comment by coreation** [comment]
True, I'm not going to assign it for the 5 december release though, but I think it could be in one of the minor versions very soon (5.12.x)

**Comment by coreation** [comment]
I've been thinking about this and I think it's best not to changes this for the following reason. You have the option to pass the name of the sheet you want to publish, meaning only that data should be public, other sheets may not be meant to. If you want to change the default name, it can be done in the framework itself, just picking the first sheet of an Excel might cause trouble. e.g. if someone typed their sheet name wrong, the first sheet gets published.

**Comment by DieterDePaepe** [comment]
I don't agree. Default option should work for most users. When using the name, it only works for people who have not renamed any sheet and are using an English Excel.

Letting them choose the sheet page to publish is perfectly combinable:
- If a sheet name is given and it exists: publish that sheet
- If a sheet name is given and it doesn't exist: fail to publish
- If no sheet name is given: use the first sheet

**Comment by coreation** [comment]
So you'd vote to leave the default value just empty and pick the first sheet if they don't choose any sheet name?

**Comment by DieterDePaepe** [comment]
Yes.

**Comment by coreation** [comment]
Done!
