### ISSUE TITLE
Error after apparently successful installation

### ISSUE THREAD

**Issue by rossjones** [tdt/core#366]
I followed the instructions at http://docs.thedatatank.com/5.12/installation to install datatank in a VM.  And everything went smoothly.

However, the browser just shows:

```
Error in exception handler.
```

There is nothing in app/storage/logs/ nor in /var/logs/apache2/error.log

**Comment by coreation** [comment]
Hi @rossjones did you fill out the database configuration? I know sometimes configuration messes the error logging up in Laravel4.

**Comment by coreation** [comment]
I did the clean install again, with database configuration (think you might have that covered) and no problems here. What php version are you running?

**Comment by rossjones** [comment]
Yes, looks like it was permissions on the laravel log file (even after I did the chmod), which was masking permissions problems in ``` /.../core/app/storage/views```.

I'll figure it out from here, it's probably just VM issues now. 

Thanks for your help.

**Comment by coreation** [comment]
No problem, let me know if you run into anything else.
