### ISSUE TITLE
Error in TDT 5.12: Class 'Memcached' not found

### ISSUE THREAD

**Issue by erikap** [tdt/core#377]
After installation of The Datatank 5.12 following the official installation guide, I got the following error:
```
PHP Fatal error:  Class 'Memcached' not found in /app/tdt-core/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php on line 44
```

Installation of the package `php5-memcached` seems to solve the problem. See also http://stackoverflow.com/questions/27991908/php-5-4-laravel-class-memcached-not-found.

**Comment by coreation** [comment]
Hi @erikap! Correct a couple of dependencies have been changed and documented in [docs](http://docs.thedatatank.com/5.12/installation)! If that suits you enough, you can close the issue.

**Comment by erikap** [comment]
Hi @coreation, I followed the [docs](http://docs.thedatatank.com/5.12/installation), but `php5-memached` is not listed in the `apt-get install`. Note that `php5-memcache` and `php5-memcached` are not the same.

**Comment by pietercolpaert** [comment]
Indeed! That's probably a typo. Should have been php5-memcached there, the php5-memcache (someone out there must know why ;))

**Comment by coreation** [comment]
Indeed php5-memcache(d) are not the same, it's a typo. However like @erikap mentioned php5-memcached might not work, instead should:

pecl install memcached

Thanks for swapping it to the docs issues list ;)
