### ISSUE TITLE
Field 'contact_point' doesn't have a default value

### ISSUE THREAD

**Issue by bjdmeest** [tdt/core#388]
When doing `php artisan db:seed --class=DemoDataSeeder`, I get the exception `Field 'contact_point' doesn't have a default value`.

When changing in the database, table `definitions`, field `contatct_point` to allow for NULL, `php artisan db:seed --class=DemoDataSeeder` is executed without error.
So I guess this is either resolved by a better configuration of the migration(, or a better seeding of the database)

**Comment by coreation** [comment]
The contact_point should be nullable in the migration. Thanks for reporting!
