### ISSUE TITLE
Real time data?

### ISSUE THREAD

**Issue by cphsolutionslab** [tdt/core#389]
How does the Datatank handle realtime data?

I've got a dataset - currently stored in a PostgreSQL - which gets updated every 5 seconds with around 3000 records.

(couldn't find anywhere else to ask such question, sorry)

**Comment by pietercolpaert** [comment]
You can use our generic SQL source and write an SQL query for the output you want. Tdt tries to keep itself scalable by making sure everything is cacheable. If you say the data doesn't change for each 5 seconds, you can configure this as well.

**Comment by coreation** [comment]
Hi @cphsolutionslab, like Pieter said, TDT will execute the underlying SQL query that you configure. You can also set a cache value, which defines for how many minutes a certain response should be cached. Just from the top of my head, I don't think we support caching in seconds.
