### ISSUE TITLE
Demo data install fails

### ISSUE THREAD

**Issue by KevinCoworks** [tdt/core#419]
Using `php artisan db:seed --class=DemoDataSeeder ` as mentioned on [http://docs.thedatatank.com/5.6/installation](http://docs.thedatatank.com/5.6/installation ) results in an error `PHP Fatal error:  Call to undefined function muka\ShapeReader\dbase_open() in <serverdir>/web/vendor/muka/shape-reader/src/DbfFile.php on line 60`

This happens after `Published a CSV dataset.
Published a JSON dataset.
Published an XML dataset.`

**Comment by coreation** [comment]
hi @KevinCoworks this is probably because you don't have the dbase PHP extension configured, can you check? It's in the last of the list of system requirements in the documentation.

**Comment by KevinCoworks** [comment]
That is indeed the case, my apologies

**Comment by coreation** [comment]
No problem :)
