### ISSUE TITLE
support for GeoJSON?

### ISSUE THREAD

**Issue by joostschouppe** [tdt/core#422]
Hi,
Does the current version support GeoJSON as an output format?

On our Antwerp version, the JSON output for our geodata is not compatible with any standard. Is there anything we should do on our side to make that work or does it need work on your side first?

**Comment by pietercolpaert** [comment]
I guess just update?

**Comment by joostschouppe** [comment]
Any idea since when this is available? (so I can confirm lack of update is
the issue on our version)

Op 20 jan. 2017 18:35 schreef "Pieter Colpaert" <notifications@github.com>:
