### ISSUE TITLE
What's the DCAT_AP URI of the demo site?

### ISSUE THREAD

**Issue by aborruso** [tdt/core#447]
I have no result with 

    http://demo.thedatatank.com/api/dcat

Thank you

**Comment by coreation** [comment]
Hi @aborruso , the demo is working on an old version at the moment for testing purposes, https://datatank.stad.gent/4/api/dcat is live data from the city of Ghent and should provide a valid DCAT feed.

**Comment by aborruso** [comment]
Thank you @coreation !
